default-profiles = ["ci", "windows", "linux"]
paths = "tests"
output-dir = "output"
languages = ["german"]

[env]
SOME_ENV_VAR = "some value"

[variables]
HEADLESS = "Yes"

[profiles.test-stage]
hidden = true

[profiles.test-stage.extend-variables]
URL = "https://todomvc.com/examples/react/dist/"

[profiles.dev-stage]
hidden = true

[profiles.dev-stage.extend-variables]
URL = "https://todomvc.com/examples/emberjs/todomvc/dist/"

[profiles.windows]
enabled.if = "platform.system()!='Windows'"
extend-variables = { OS = "WINDOWS" }

[profiles.linux]
enabled.if = "platform.system()=='Linux'"
extend-variables = { OS = "LINUX" }

[profiles.ci]
enabled = { if = "environ.get('CI')" }

[profiles.ci.extend-variables]
IN_CI = "yes"

[profiles.dev]
precedence = 100

[profiles.dev.extend-variables]
BROWSER = "firefox"
HEADLESS = "No"
